name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app1/requirements.txt

    - name: Run Flask app and test it
      run: |
        cd app1
        nohup python app.py > flask.log 2>&1 &
        echo "Uygulama başlatıldı, yanıt bekleniyor..."
        
        for i in {1..10}; do
          if curl --silent http://127.0.0.1:5000/; then
            echo "✅ Flask çalışıyor!"
            exit 0
          fi
          echo "⏳ Sunucu henüz hazır değil, tekrar denenecek..."
          sleep 2
        done

        echo "❌ Flask uygulaması başlatılamadı. Log çıktısı:"
        cat flask.log
        exit 1
