name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app1/requirements.txt

    - name: Run Flask and test
      run: |
        cd app1
        export FLASK_APP=app.py  # Eğer uygulama dosyanızın adı farklıysa burayı değiştirin
        nohup flask run --host=127.0.0.1 > flask.log 2>&1 &
        sleep 5
        curl http://127.0.0.1:5000/
