name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app1/requirements.txt

    - name: Run Flask and test
      run: |
        cd app1
        export FLASK_APP=app.py
        export FLASK_ENV=development
        nohup flask run --host=127.0.0.1 --port=5000 > flask.log 2>&1 &
        for i in {1..10}; do
          if curl --silent http://127.0.0.1:5000/; then
            echo "Flask uygulaması başarılı şekilde yanıt verdi."
            exit 0
          fi
          echo "Sunucu hazır değil, yeniden deneniyor..."
          sleep 1
        done
        echo "Flask uygulaması başlatılamadı."
        cat flask.log
        exit 1
